#!/usr/bin/env bash

# set Keyboard Layout
setxkbmap -layout us


##########################
# bspwm color settings #
##########################

foreground=#acb0d0
background=#1a1b26
color0=#32344a
color1=#f7768e
color2=#9ece6a
color3=#e0af68
color4=#7aa2f7
color5=#ad8ee6
color6=#0db9d7
color7=#787c99
color8=#444b6a
color9=#ff7a93
color10=#b9f27c
color11=#ff9e64
color12=#7da6ff
color13=#bb9af7
color14=#449dab
color15=#acb0d0


##########################
# bspwm general settings #
##########################

bspc wm -O DisplayPort-1 DisplayPort-0
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DisplayPort-1 -d 6 7 8 9 10

bspc config border_width 2
bspc config top_padding 2
bspc config right_padding 2
bspc config left_padding 2
bspc config bottom_padding 2
bspc config window_gap 4
bspc config top_monocle_padding 2
bspc config right_monocle_padding 2
bspc config left_monocle_padding 2
bspc config bottom_monocle_padding 2

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

# follow mouse focus
bspc config focus_follows_pointer true

# disable swapping workspaces on app launch
bspc config ignore_ewmh_focus true


################
# bspwm colors #
################

bspc config normal_border_color "$color0"
bspc config focused_border_color "$color14"
bspc config active_border_color "$color6"
bspc config urgent_border_color "$color1"
bspc config presel_border_color "$color3"
bspc config presel_feedback_color "$color12"


#############################
# assign Program Workspaces #
#############################

bspc rule -a steam desktop='^3' follow=off
bspc rule -a steamwebhelper desktop='^3' follow=off
bspc rule -a Lutris desktop='^3' follow=off
bspc rule -a virt-manager desktop='^4' follow=off
bspc rule -a Virt-manager desktop='^4' follow=off
bspc rule -a VirtualBox Manager desktop='^4' follow=off


########################
# set apps to floating #
########################

bspc rule -a About state=floating
bspc rule -a Gufw.py state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Arandr state=floating
bspc rule -a Pulseeffects state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a copyq state=floating
bspc rule -a Yad state=floating
bspc rule -a nifskope.exe state=floating


################################
# Assign wineserver Workspaces #
################################

bspc rule -a steam_app_22380 desktop='^5' follow=off
bspc rule -a wow.exe desktop='^5' follow=off
bspc rule -a Overwatch.exe desktop='^5' follow=off
bspc rule -a battle.net.exe desktop='^5' follow=off
bspc rule -a nifskope.exe desktop='^5' follow=off


#######################
# custom startup apps #
#######################

